### ISSUE TITLE
Windows compile detected as a virus

### ISSUE THREAD

**Issue by paolo2504** [larspalo/GOODF#1]
Hi. Just tried to launch r0300 compile for x86-windows detached from here. It is detected as a virus by Microsoft defender.

**Comment by larspalo** [comment]
It's a known issue as noted in https://github.com/GrandOrgue/grandorgue/discussions/1394#discussioncomment-5021181 but I unfortunately don't know exactly why.

However, I again sumbitted the exectuable to virustotal.com for testing and the report (as you can see from the attached screenshot)

![Skärmbild från 2023-03-04 16-37-11](https://user-images.githubusercontent.com/6173941/222915155-005e86bd-eae3-496d-bd68-08dc90cf0ba1.png)

is again suggesting that the detection is a false positive.

**Comment by larspalo** [comment]
@paolo2504 New release builds (starting with v0.4.0) are now done on GitHub runners. Please test and see if the false positives are still reported or if we can consider this issue as fixed.

**Comment by paolo2504** [comment]
Now it correctly works. Thanks.
