### ISSUE TITLE
Opening wav files for noises,etc.

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#17]
I create a rank with one note for a noise such as a blower or a clochette.  When I try to load a specific .wav file from a directory I am not able to choose it.  For example I have a clochette directory with files: 51.wav, 52.wav, 61.wav, 62.wav.

If I press the "Add morre sampes from..." button with the first midi note number =36, no samples are added. If I set the first midi note number to zero the same thing happens.  If I set the first midi note number to 1, then 51.wav and 61.wav are added.  If I set midi note number to 2,  the same files are loaded again.  There does not appear to be any way to select all four files, or in other potential scenarios to select one of several files in a directory.

**Comment by larspalo** [comment]
Can you select the Pipe001, right click and select "Add new attack from..." (or just select the Pipe001 and hit Ctrl+A) and add the sample manually?

Just tested loading a 52.wav with using the "Create new pipes by MIDI nbr from..." with the First Midi Note: set to 52 and it works fine. Then using "Add more samples from..." added the (single) sample to the pipe again. So I'm not understanding why it wouldn't work for you if you set the first midi note to the actual number you want to start from...

However, you've found a bug in the sample detection from the midi number. With first Midi note set to 1 the first sample should have only been named 1.wav or 01.wav or 001.wav or something similar. The fact that 1 would match any number containing 1 as last digit is a problem I'll have to fix.

**Comment by larspalo** [comment]
Looking at the code, it's pretty obvious! The first number matching against file name is currently done like *%i*.* for the Midi first note. That means anything before the first midi note number and anything after will match!

In a next sorting step only wav or wv files (case insensitive) are kept. I think I'll have to add a new additional number check to sort out more exactly the precise number match without such greedy globbing.

**Comment by davidgritter** [comment]
Yes, the method you suggest to load the samples by right clicking on the pipe works fine.

**Comment by larspalo** [comment]
I've committed changes that should match the number in the file name much more exactly now.

**Comment by larspalo** [comment]
@davidgritter Do you think this issue could be closed as fixed?

**Comment by davidgritter** [comment]
Yes this can be closed.  Now when specifying the midi note I can load the correct sample, then change the midi note to load the next sample, etc, all from the main window, as well as by right clicking on the pipe to add a sample.
