### ISSUE TITLE
Setters not working

### ISSUE THREAD

**Issue by William-Purvis** [larspalo/GOODF#20]
Having given up trying to get Divisionals working I am trying to use SetterXXXDivisonalYYY in my ODF.
When I create a new one in GOODF it always comes up as Setter000Divisional000, and lacks positional
info. I edit the PositionX and PositionY into the ODF but GOODF just discards it.

**Comment by William-Purvis** [comment]
Just spotted  the Divisional and Combination fields! Apologies

**Comment by William-Purvis** [comment]
Re-opening: My comment about losing positional information is still a problem. Setting PositionX and PositionY in GOODF is ignored, and if I add them in to the ODF afterwards, they do get loaded and appear in the GUI, but are again discarded on saving.

Just load and save is enough to loose them.

**Comment by larspalo** [comment]
Do you remember to tab out of the PositionX and PositionY spinctrls? Are you using a recent GOODF version?

**Comment by William-Purvis** [comment]
Yes, version=0.5.0

**Comment by William-Purvis** [comment]
Propose a fix:
GUIDivisional:
44,47d43
< 	if (m_positionX != -1)
< 		outFile->AddLine(wxT("PositionX=") + wxString::Format(wxT("%i"), m_positionX));
< 	if (m_positionY != -1)
< 		outFile->AddLine(wxT("PositionY=") + wxString::Format(wxT("%i"), m_positionY));

Seems to work for me.

**Comment by larspalo** [comment]
@William-Purvis Yes, that's a good catch, thanks! I forgot to add those lines for the GUIDivisional. I've committed the fix now!
