### ISSUE TITLE
loading tremmed release samples

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#3]
I created a tree of samples inclucing normal attacks, normal releases, tremmed attacks, and tremmed releases as shown in the referenced png.   In this case there were three normal releases, rel00220, rel 00450, rel99999, and two tremmed releases rel00220, rel99999.  When I import these into a rank all the correct wav files are imported except those in the tremmed release rel00220 directory.  I then added a tremmed rel00450 directory and repeated the import into a rank. In this case both the tremmed rel00220 and the tremmed rel99999 are correctly imported, but not the tremmed rel00450 directory.  It seems, perhaps, that the tremmed release import imports one less directory than it finds?

![sampletree](https://user-images.githubusercontent.com/94871928/223493806-92e982ba-872b-40ec-9eeb-39519d86bf0f.png)

**Comment by larspalo** [comment]
@davidgritter Ok, I can confirm that something is wrong when using the "Create new pipes by MIDI nbr from...", but for me the _last_ folder rel99999 was not added for the trem. I'll investigate and see what's wrong.

If I add the tremulant samples separately by the "Add tremulant samples from..." then every folder is detected.

**Comment by larspalo** [comment]
@davidgritter I think I've fixed this issue with the latest commit (51). Please confirm that the detection is working now as it should (or not).

**Comment by davidgritter** [comment]
I confirm that this is working correctly now

**Comment by larspalo** [comment]
Great! I've also applied the same fix to the "Add more samples from..." detection.
