### ISSUE TITLE
Another Save Bug

### ISSUE THREAD

**Issue by Bumblebee001** [larspalo/GOODF#37]
I cannot get any selected coupler to be saved in the on position for a Tutti piston:
![image](https://github.com/larspalo/GOODF/assets/6999990/519ab363-12bb-43b8-8fd0-252ca8de3296)
Stops & tremulants OK

**Comment by larspalo** [comment]
Right, it should be fixed by https://github.com/larspalo/GOODF/commit/6a58d4daeeaaeaf944bf33ef6695075de34b8bad but if you don't compile from source you'll have to wait until next release and I'd like to fix a few more things before I'll trigger a new build.

**Comment by larspalo** [comment]
@Bumblebee001 Do you consider this issue fixed?

**Comment by Bumblebee001** [comment]
Which issue was that?

**Comment by larspalo** [comment]
Just that the (on) state of a coupler wasn't saved in an odf general. That was fixed many months ago. I'm just cleaning up so that I have a clearer view of what to work on for the future.

**Comment by Bumblebee001** [comment]
Ok, thanks for the clarification.

I must have helped in quite a few things to get GOODF to what it is today.
I’ve almost lost track. However it is still quite some way away from where
I’d like to see it (& grandorgue). Although my hopes have largely been
dashed to ever see them implemented, I trust that some day they will be
dealt with accordingly. After this sampleset and another yet to follow, I
doubt I will continue creating sample sets for many reasons. As I grow
older negotiating spiral staircases in churches has become increasingly
difficult, add to that the things I need to carry up those stairwells - and
not just equipment… There are other issues that will negatively impact this
project.

I’ll soldier on as far as I can go and I hope others will pick up where we
have left off.

Mark

**Comment by larspalo** [comment]
> I’ll soldier on as far as I can go and I hope others will pick up where we
have left off.

That is all we ever can do.

"So place your hand in the hand of another,
and if God wills it, your dream moves on...forever."

**Comment by Bumblebee001** [comment]
😌
