### ISSUE TITLE
Swell Pedal

### ISSUE THREAD

**Issue by Bumblebee001** [larspalo/GOODF#38]
Another ? bug is the swell pedal...... It does not work properly. It either does not respond at all or responds temporarily and unpredictably. I succeeded in correcting the behaviour. The default value set for MouseRectHeight was 1 instead of max of 48 (even though the image is 61).

**Comment by larspalo** [comment]
Could you please describe the steps to (always) reproduce the issue? So far I've not encountered anything like that myself.

But as a side note, the enclosure swell pedal in GO is best operated by MIDI signals or if you need to use a mouse - use the mouse wheel to adjust the position. While it's possible to click and drag the pedal - it easily/usually misbehaves when doing that.

**Comment by larspalo** [comment]
@Bumblebee001 As you've not provided any further information about this issue, do you consider it fixed?

**Comment by Bumblebee001** [comment]
Forget it for the time being. I will report to you if I encounter the issue
again.
