### ISSUE TITLE
Creating GUI labels

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#5]
If I create several GUI labels, and edit the first one to put it above or centered between drawstop columns by setting Free X pos: to No and FreeY pos to No, everything works fine.  However if I then try to edit the second GUI label, Free X pos and Free Y pos are already set to No, but the following choices are not active:
At Top of drawstop columns
Span column to right
DispDrawstopCol

I need to toggle  Free X or Free Y to get these active.  I would assume that the settings for FreeX and FreeY in one label should not affect the other labels in any way.

**Comment by larspalo** [comment]
Yes, that's a bug. I'll fix it with next commit.

**Comment by larspalo** [comment]
@davidgritter Have you tested this since the fix I committed?
