### ISSUE TITLE
wxSpinCtrlDouble precision and increment

### ISSUE THREAD

**Issue by larspalo** [larspalo/GOODF#50]
Do we really need these to go up by 0.000001 step at a time? 

Wouldn't it make more sense to go in whole numbers rather than 10 e-6 fractions?

_Originally posted by @Bumblebee001 in https://github.com/larspalo/GOODF/discussions/45_

**Comment by larspalo** [comment]
Perhaps there might be a way to keep floating point precision and anyway make the increments in whole steps. The wxSpinCtrlDouble is intially created with 0.000001 increment in the constructor, then afterwards calling:

```
	wxSpinCtrlDouble->SetDigits(6);
	wxSpinCtrlDouble->SetIncrement(1.0f);
```

seem to allow both decimals entry and also increment by whole steps. Needs testing before implementation!

**Comment by larspalo** [comment]
Should be fixed with d2f4279f46a9ab60be0d1b551bc9cf89dc1525a3.

**Comment by Bumblebee001** [comment]
Ok, thanks. Much obliged for seeing the worth of my observations.

**Comment by larspalo** [comment]
@Bumblebee001 With the 0.7.2 release this should have been addressed. Do you think this issue is fixed?

**Comment by Bumblebee001** [comment]
I haven’t tried yet

**Comment by Bumblebee001** [comment]
Yes - that makes a lot more sense. Thanks.
