### ISSUE TITLE
Drawstop, Switch, Coupler, Tremulant text always displayed in their Gui elements

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#6]
There does not appear to be any way to prevent The display of the name of these elements on the GUI panel.  In the ODF file the GUIelementXXX can be edited to remove this text so that an external graphical ON and OFF image that already contains the name can be specified.

**Comment by larspalo** [comment]
It's done by setting TextBreakWidth to 0.

**Comment by larspalo** [comment]
Also, the DispLabelText can be used to override the original object name for display. But to completely eliminate any displayed text, the TextBreakWidth must be set to zero.

**Comment by larspalo** [comment]
@davidgritter Can we consider this issue as fixed?
