### ISSUE TITLE
Program suddenly closes without saving

### ISSUE THREAD

**Issue by Bumblebee001** [larspalo/GOODF#60]
When I was editing the odf I was working on to create another version of the set, and deleted all the switches, and moved to the stops to edit them, the program kept crashing at that point, closing abruptly, without warning.

I was able to save *before* moving on to edit the stops when the crash occurred. After this it was then possible to open the odf and edit the stops as inputs.

Mark

**Comment by larspalo** [comment]
Thanks for reporting, I can confirm that this bug is real and I'll investigate/fix it as soon as I've finished working on the flexible pipe loading dialog.

**Comment by Bumblebee001** [comment]
Welcome!🙏

**Comment by larspalo** [comment]
Should be fixed with f0c6ecd0e93fc29f2c4ea18ba88f9990fca285ef.
