### ISSUE TITLE
Manual placement

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#7]
Manual placement in the Main panel appears to be ordered from the bottom up in the order in which the GUI element for each manual object is created.  Thus, for example, the Pedal can appear as a keyboard at the top, even though the 'This manual is pedal' box has been checked when the manual was defined.  I would expect that the order of the manuals in the GUI would be determined by the manual's MIDI input number parameter, or that some other mechanism to define and change the order would be present.

**Comment by larspalo** [comment]
From the GO help on Manuals:

> Best practice is to specify the visible manuals in the order of appearance, lowest first.

This is of course only for the structural build up and how the default display metrics layout system works. (Pedal is always [Manual000] and then in order [Manual001] for the first manual and [Manual002] for the second and so on).

On the panels it's perfectly possible to visually place the manuals in any order one may like, especially by using the free positioning of PositionX and PositionY. To ensure correct placement, according to the default layout, the boolean value of "Has Pedals" must be ticked for panel too.

In GOODF I decided that only the very first manual could structurally be assigned as the pedal (on any other manual the checkbox is disabled). This makes it easier to conform to the GO manual numbering system and no confusion should arise. But on the panels it's up to the user to decide how the manuals will be displayed.

A possible improvement though, is that if the [Manual000] is populated in the structural section (the very first manual has the 'This manual is pedal' checkbox ticked), the main panel could automatically update the required boolean value of HasPedals=Y. But on the other hand - I think that the user should have the freedom to do whatever he/she likes within the limitations of GrandOrgue ODF and not be forced to do only "the right" choices...

**Comment by larspalo** [comment]
@davidgritter Can we consider this issue as fixed?

**Comment by davidgritter** [comment]
As I understand it, and have written in the help, the manuals need to be added as Gui elements in the order in which you want them to display from the bottom up if not manually placing them.   If that is correct then this can be closed
