### ISSUE TITLE
Testing image loading for Gui elements

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#8]
When testing the ability to load custom images for GUI elements by clicking the browse button, i can find, for example *.bmp images, but not *.BMP images, often used in hauptwerk organ definitions (case is not important in Windows search) Can the browse be made case insensitive?

**Comment by larspalo** [comment]
Yes, I did that for the Gui Manual panel. There's no simple way to make the wildcard case insensitive for the wxfiledialog (on both wxGTK and to still be cross platform), but one can overload them to give that impression. For the Gui Manual I added *.bmp, *.BMP and *.Bmp versions (for all supported file types), do you think that's enough for all image loading elements?

**Comment by larspalo** [comment]
Test the latest commit and see if that's good enough.

**Comment by davidgritter** [comment]
seems to be ok to me.   I have seen .bmp , .BMP, .wav, .WAV in the same organ packages several times and this version picks up both.

**Comment by larspalo** [comment]
Ok, then I close this issue for now.
